<a href="https://colab.research.google.com/github/kotatech24/AIML/blob/main/day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
documents = [
    "I love machine learning",
    "Machine learning is fun",
    "I love coding"
]

In [2]:
tokens = [doc.lower().split() for doc in documents]
print(tokens)

[['i', 'love', 'machine', 'learning'], ['machine', 'learning', 'is', 'fun'], ['i', 'love', 'coding']]


In [3]:
vocab = sorted(set(word for doc in tokens for word in doc))
print(vocab)

['coding', 'fun', 'i', 'is', 'learning', 'love', 'machine']


In [4]:
import pandas as pd

bow_vectors = []

for doc in tokens:
    word_count = dict.fromkeys(vocab, 0)
    for word in doc:
        word_count[word] += 1
    bow_vectors.append(word_count)

df = pd.DataFrame(bow_vectors)
print(df)

   coding  fun  i  is  learning  love  machine
0       0    0  1   0         1     1        1
1       0    1  0   1         1     0        1
2       1    0  1   0         0     1        0


In [5]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(X.toarray())


['coding' 'fun' 'is' 'learning' 'love' 'machine']
[[0 0 0 1 1 1]
 [0 1 1 1 0 1]
 [1 0 0 0 1 0]]


In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(documents)

print(tfidf.get_feature_names_out())
print(X_tfidf.toarray())

['coding' 'fun' 'is' 'learning' 'love' 'machine']
[[0.         0.         0.         0.57735027 0.57735027 0.57735027]
 [0.         0.5628291  0.5628291  0.42804604 0.         0.42804604]
 [0.79596054 0.         0.         0.         0.60534851 0.        ]]


In [7]:
print(type(X))

<class 'scipy.sparse._csr.csr_matrix'>


In [8]:
print(X.data)      # non-zero values
print(X.indices)   # column indices
print(X.indptr)    # row pointer


[1 1 1 1 1 1 1 1 1]
[4 5 3 5 3 2 1 4 0]
[0 3 7 9]


In [9]:
from scipy.sparse import csr_matrix
import numpy as np

dense = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 2, 0]
])

csr = csr_matrix(dense)

print("Data:", csr.data)
print("Indices:", csr.indices)
print("Indptr:", csr.indptr

_IncompleteInputError: incomplete input (4221965878.py, line 14)

In [10]:
documents = [
    "Win money now",
    "Limited time offer",
    "Claim your prize now",
    "Congratulations you won a lottery",
    "Exclusive offer just for you",
    "Call now to win cash",
    "Hey how are you",
    "Let's meet tomorrow",
    "Are you coming to the meeting",
    "Please review the document",
    "Lunch at 1 pm",
    "Can we reschedule the meeting"
]

labels = [1,1,1,1,1,1, 0,0,0,0,0,0]



In [11]:
import pandas as pd

# Tokenization
tokens = [doc.lower().split() for doc in documents]

# Vocabulary
vocab = sorted(set(word for doc in tokens for word in doc))

# Create BoW
bow_vectors = []
for doc in tokens:
    word_count = dict.fromkeys(vocab, 0)
    for word in doc:
        word_count[word] += 1
    bow_vectors.append(word_count)

df_bow = pd.DataFrame(bow_vectors)
print(df_bow)

    1  a  are  at  call  can  cash  claim  coming  congratulations  ...  \
0   0  0    0   0     0    0     0      0       0                0  ...   
1   0  0    0   0     0    0     0      0       0                0  ...   
2   0  0    0   0     0    0     0      1       0                0  ...   
3   0  1    0   0     0    0     0      0       0                1  ...   
4   0  0    0   0     0    0     0      0       0                0  ...   
5   0  0    0   0     1    0     1      0       0                0  ...   
6   0  0    1   0     0    0     0      0       0                0  ...   
7   0  0    0   0     0    0     0      0       0                0  ...   
8   0  0    1   0     0    0     0      0       1                0  ...   
9   0  0    0   0     0    0     0      0       0                0  ...   
10  1  0    0   1     0    0     0      0       0                0  ...   
11  0  0    0   0     0    1     0      0       0                0  ...   

    review  the  time  t

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    lowercase=True,
    stop_words='english',
    ngram_range=(1,2)   # captures phrases like "win money"
)

X = tfidf.fit_transform(documents)
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 42 stored elements and shape (12, 39)>
  Coords	Values
  (0, 34)	0.5190584835624306
  (0, 22)	0.6043915496769748
  (0, 36)	0.6043915496769748
  (1, 14)	0.4594336046639039
  (1, 31)	0.4594336046639039
  (1, 23)	0.3945669165327051
  (1, 15)	0.4594336046639039
  (1, 32)	0.4594336046639039
  (2, 1)	0.5773502691896257
  (2, 26)	0.5773502691896257
  (2, 2)	0.5773502691896257
  (3, 5)	0.4472135954999579
  (3, 37)	0.4472135954999579
  (3, 16)	0.4472135954999579
  (3, 6)	0.4472135954999579
  (3, 38)	0.4472135954999579
  (4, 23)	0.3945669165327051
  (4, 8)	0.4594336046639039
  (4, 11)	0.4594336046639039
  (4, 9)	0.4594336046639039
  (4, 24)	0.4594336046639039
  (5, 34)	0.5190584835624306
  (5, 0)	0.6043915496769748
  (5, 35)	0.6043915496769748
  (6, 10)	1.0
  (7, 12)	0.4472135954999579
  (7, 19)	0.4472135954999579
  (7, 33)	0.4472135954999579
  (7, 13)	0.4472135954999579
  (7, 20)	0.4472135954999579
  (8, 3)	0.6043915496769748
  (8, 2

In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X, labels)


LogisticRegression()

In [14]:
# new_text = ["Congratulations! you have won a prize"]
new_text = ["America is big"]

new_vector = tfidf.transform(new_text)
prediction = model.predict(new_vector)

print("Spam" if prediction[0] == 1 else "Not Spam")

Not Spam


In [ ]:
# Tokenization
# Stopword removal
# Stemming / Lemmatization
# POS tagging (optional insight)
# Chunking (phrase extraction)
# Vectorization (TF-IDF)
# Model training

In [15]:
documents = [
    "I absolutely loved the product, it works amazingly well",
    "This is the worst purchase I have ever made",
    "The quality is decent but not great",
    "I am very happy with the performance",
    "Terrible experience, waste of money",
    "It is okay, nothing special",
    "This product is amazing",
    "Great quality and excellent performance",
    "I love this product it is fantastic",
    "This is the worst product ever",
    "Absolutely terrible experience",
    "Very bad quality and disappointing",
    "I hate this product",
    "good product", "bad product"
]

labels = [1, 0, 0, 1, 0, 0,1,1,1,0, 0,0, 0,1,0]

In [16]:
import nltk
from nltk.tokenize import word_tokenize

tokens = [word_tokenize(doc.lower()) for doc in documents]
print(tokens)

LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [19]:
import nltk
from nltk.tokenize import word_tokenize

tokens = [word_tokenize(doc.lower()) for doc in documents]
print(tokens)

[['i', 'absolutely', 'loved', 'the', 'product', ',', 'it', 'works', 'amazingly', 'well'], ['this', 'is', 'the', 'worst', 'purchase', 'i', 'have', 'ever', 'made'], ['the', 'quality', 'is', 'decent', 'but', 'not', 'great'], ['i', 'am', 'very', 'happy', 'with', 'the', 'performance'], ['terrible', 'experience', ',', 'waste', 'of', 'money'], ['it', 'is', 'okay', ',', 'nothing', 'special'], ['this', 'product', 'is', 'amazing'], ['great', 'quality', 'and', 'excellent', 'performance'], ['i', 'love', 'this', 'product', 'it', 'is', 'fantastic'], ['this', 'is', 'the', 'worst', 'product', 'ever'], ['absolutely', 'terrible', 'experience'], ['very', 'bad', 'quality', 'and', 'disappointing'], ['i', 'hate', 'this', 'product'], ['good', 'product'], ['bad', 'product']]


In [18]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [22]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

filtered_tokens = [
    [word for word in doc if word.isalpha() and word not in stop_words]
    for doc in tokens
]

print(filtered_tokens)

[['absolutely', 'loved', 'product', 'works', 'amazingly', 'well'], ['worst', 'purchase', 'ever', 'made'], ['quality', 'decent', 'great'], ['happy', 'performance'], ['terrible', 'experience', 'waste', 'money'], ['okay', 'nothing', 'special'], ['product', 'amazing'], ['great', 'quality', 'excellent', 'performance'], ['love', 'product', 'fantastic'], ['worst', 'product', 'ever'], ['absolutely', 'terrible', 'experience'], ['bad', 'quality', 'disappointing'], ['hate', 'product'], ['good', 'product'], ['bad', 'product']]


In [21]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [23]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

stemmed_tokens = [
    [stemmer.stem(word) for word in doc]
    for doc in filtered_tokens
]

print(stemmed_tokens)

[['absolut', 'love', 'product', 'work', 'amazingli', 'well'], ['worst', 'purchas', 'ever', 'made'], ['qualiti', 'decent', 'great'], ['happi', 'perform'], ['terribl', 'experi', 'wast', 'money'], ['okay', 'noth', 'special'], ['product', 'amaz'], ['great', 'qualiti', 'excel', 'perform'], ['love', 'product', 'fantast'], ['worst', 'product', 'ever'], ['absolut', 'terribl', 'experi'], ['bad', 'qualiti', 'disappoint'], ['hate', 'product'], ['good', 'product'], ['bad', 'product']]


In [24]:
from nltk import pos_tag

pos_tags = [pos_tag(doc) for doc in stemmed_tokens]
print(pos_tags)

LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger_eng not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger_eng')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger_eng/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [25]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


True

In [26]:
from nltk.chunk import RegexpParser

grammar = "NP: {<JJ>*<NN>}"  # adjective + noun
chunk_parser = RegexpParser(grammar)

for doc in pos_tags:
    tree = chunk_parser.parse(doc)
    print(tree)

NameError: name 'pos_tags' is not defined

In [27]:
processed_docs = [" ".join(doc) for doc in stemmed_tokens]
print(processed_docs)

['absolut love product work amazingli well', 'worst purchas ever made', 'qualiti decent great', 'happi perform', 'terribl experi wast money', 'okay noth special', 'product amaz', 'great qualiti excel perform', 'love product fantast', 'worst product ever', 'absolut terribl experi', 'bad qualiti disappoint', 'hate product', 'good product', 'bad product']


In [28]:
# from sklearn.feature_extraction.text import TfidfVectorizer

# tfidf = TfidfVectorizer(ngram_range=(1,2))
# X = tfidf.fit_transform(processed_docs)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    lowercase=True,
    stop_words='english',   # safe
    ngram_range=(1,2)
)
X = tfidf.fit_transform(processed_docs)

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(
    X, labels, test_size=0.3, random_state=42
)

model = LogisticRegression(class_weight='balanced')
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [30]:
# test_sentence = ["This product is absolutely amazing and great"]
test_sentence = ["This is worst product"]

# Apply same preprocessing
test_tokens = word_tokenize(test_sentence[0].lower())
test_filtered = [w for w in test_tokens if w.isalpha() and w not in stop_words]
test_stemmed = [stemmer.stem(w) for w in test_filtered]

test_processed = [" ".join(test_stemmed)]

test_vector = tfidf.transform(test_processed)
prediction = model.predict(test_vector)

print("Positive" if prediction[0] == 1 else "Negative")

Negative
